services:
  app:
    build: .
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
    # volumen nombrado para evitar problemas de permisos
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  uploads_data:
