services:
  app:
    build: .
    ports:
      - "3010:3000"   # <-- publica 3000 del contenedor en el 3010 del host
    environment:
      - NODE_ENV=production
    volumes:
      - uploads_data:/app/uploads
    restart: unless-stopped

volumes:
  uploads_data:
